/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal.View;

import ProyectoFinal.UI;

/**
 *
 * @author gabyt
 */
public class AgregarMateria extends javax.swing.JFrame {

    /**
     * Creates new form CrearMaterias
     */
    public AgregarMateria() {
        initComponents();
        setSize(400, 590);
        setTitle("panel de opciones");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Return_Button = new javax.swing.JToggleButton();
        MateriasPreparatoria = new javax.swing.JToggleButton();
        MateriasProfesional = new javax.swing.JToggleButton();
        MateriasPosgrado = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(157, 210, 35));

        Return_Button.setForeground(new java.awt.Color(0, 0, 0));
        Return_Button.setText("Regresar");
        Return_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_ButtonActionPerformed(evt);
            }
        });

        MateriasPreparatoria.setForeground(new java.awt.Color(0, 0, 0));
        MateriasPreparatoria.setText("Preparatoria");
        MateriasPreparatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriasPreparatoriaActionPerformed(evt);
            }
        });

        MateriasProfesional.setForeground(new java.awt.Color(0, 0, 0));
        MateriasProfesional.setText("Profesional");
        MateriasProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriasProfesionalActionPerformed(evt);
            }
        });

        MateriasPosgrado.setForeground(new java.awt.Color(0, 0, 0));
        MateriasPosgrado.setText("Posgrado");
        MateriasPosgrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriasPosgradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(Return_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MateriasPosgrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MateriasProfesional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MateriasPreparatoria, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(MateriasPreparatoria)
                .addGap(28, 28, 28)
                .addComponent(MateriasProfesional)
                .addGap(26, 26, 26)
                .addComponent(MateriasPosgrado)
                .addGap(28, 28, 28)
                .addComponent(Return_Button)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MateriasPreparatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriasPreparatoriaActionPerformed
        // TODO add your handling code here:
        motorInteface.GoToMateriaPreparatoria();
        hide();
        
        
    }//GEN-LAST:event_MateriasPreparatoriaActionPerformed

    private void MateriasProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriasProfesionalActionPerformed
        // TODO add your handling code here:
        motorInteface.GoToMateriasProfesional();
        hide();
    }//GEN-LAST:event_MateriasProfesionalActionPerformed

    private void MateriasPosgradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriasPosgradoActionPerformed
        // TODO add your handling code here:
        motorInteface.GoToMateriasPosgrado();
       
        hide();
    }
         public void setMotor(UI mot) {
         motorInteface= mot;
    }//GEN-LAST:event_MateriasPosgradoActionPerformed

    private void Return_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_ButtonActionPerformed
        // TODO add your handling code here:
          motorInteface.goToOpView();
          hide();
        
    }//GEN-LAST:event_Return_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton MateriasPosgrado;
    private javax.swing.JToggleButton MateriasPreparatoria;
    private javax.swing.JToggleButton MateriasProfesional;
    private javax.swing.JToggleButton Return_Button;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
//miau miau miau meow meow nya nyaaaan XX
//                                     -- nwn unu uvu uwu QwQ TTuTT TTnTT
//                                                        ---
  private UI motorInteface;
}



